void f_socket_create(int num_arg);
void f_socket_bind(int num_arg);
void f_socket_listen(int num_arg);
void f_socket_accept(int num_arg);
void f_socket_connect(int num_arg);
void f_socket_write(int num_arg);
void f_socket_close(int num_arg);
void f_socket_release(int num_arg);
void f_socket_acquire(int num_arg);
void f_socket_error(int num_arg);
void f_socket_address(int num_arg);
void f_dump_socket_status(int num_arg);
float check_memory_usage(struct svalue *s,int num);
void f_order_alist(int num_arg);
void f_insert_alist(int num_arg);
void f_assoc(int num_arg);
void f_set_bit();
void f_clear_bit();
void f_test_bit();
void f_filter_mapping(int num_arg);
void f_filter_array(int num_arg);
int f_sscanf(int num_arg);
void f_map_mapping(int num_arg);
void f_map_array(int num_arg);
void f_sort_array(int num_arg);
void f_debug_info(int num_arg);
void f_say(int num_arg);
void f_tell_room(int num_arg);
void f_shadow();
void f__next_clone();
void f_query_snoop();
void f_extract(int num_arg);
void f_snoop(int num_arg);
void f_ed(int num_arg);
void f__super_invis(int num_arg);
void f__driver_stat();
void f__find_shortest_path(int num_arg);
struct object *f__get_clone_by_number(int);
